config/routes.rb
Rails.application.routes.draw do
  match '/users/:id',     to: 'users#show',       via: 'get'
  # resources :users, :only =>[:show, :edit]
  
#  resources :users
  root to: "posts#index"      
  
  resources :posts do
    patch :update_read_post
  end


  # devise_for :users
  devise_for :users, :path_prefix => 'd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # validates :text, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @user = current_user
    reload=0
    @posts.each do |post|
      if post.expires_at != nil
        if post.expires_at <= DateTime.now  
          post.destroy
          reload=1
        end
      end  
    end
    if reload == 1
      redirect_to posts_path
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    if params[:days].to_i==0 && params[:hours].to_i==0 && params[:minutes].to_i==0 && params[:seconds].to_i==0
      @post.expires_at =  DateTime.now + 1.hours
    else
      @post.expires_at =  DateTime.now + params[:days].to_i.days + params[:hours].to_i.hours + 
                          params[:minutes].to_i.minutes + params[:seconds].to_i.seconds
    end
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if params[:days].to_i==0 && params[:hours].to_i==0 && params[:minutes].to_i==0 && params[:seconds].to_i==0
      @post.expires_at =  DateTime.now + 1.hours
    else
      @post.expires_at =  DateTime.now + params[:days].to_i.days + params[:hours].to_i.hours + 
                          params[:minutes].to_i.minutes + params[:seconds].to_i.seconds
    end
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def update_read_post
    numPosts = current_user.readed_posts
    if numPosts == nil
      numPosts = ""
    end
    numPosts +=  " " +  params[:value] + " "
    pag = '/users/'
    pag.concat(current_user.id.to_s)
    current_user.update_attribute(:readed_posts, numPosts)
    redirect_to posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :text, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @posts = Post.all
    if current_user
      pag = '/users/'
      pag.concat(current_user.id.to_s)
      redirect_to pag
    end
  end
  
  def show
    @posts = Post.all
    @user = User.find(params[:id])
  end
  
  def edit
    @posts = Post.all
    @user = User.find(params[:id])
  end
  
  def update
    # @post = Post.find(params[:id])
    # numPosts = "1, 2, 3"
    # numPosts = current_user.prueba + ", " +  params[:user][:prueba]
    numPosts = current_user.prueba
    if numPosts == nil
      numPosts = ""
    end
    numPosts +=  " " +  params[:name] + " "
    # numPosts = params[:user][:prueba]
    pag = '/users/'
    pag.concat(current_user.id.to_s)
    # current_user.update_attributes(params[:user])
    current_user.update_attribute(:prueba, numPosts)
    redirect_to pag
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/?.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/_.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Home" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
   <div class="top-bar-container" data-sticky-container>
  <div class="sticky sticky-topbar" data-sticky data-options="anchor: page; marginTop: 0; stickyOn: small;">
    <div class="top-bar">
      <div class="top-bar-left">
        <!--<ul class="dropdown menu" data-dropdown-menu>-->
        <ul class="menu">

          <li><%= link_to "Home",   root_path %></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if current_user %>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
          <% else %>  
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>


  
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<% if current_user %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
<% else %>  
<%= link_to 'Sign up', new_user_registration_path %>
<%= link_to 'Sign in', new_user_session_path %>
<% end %>  

<%= link_to 'Posts', posts_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, placeholder: "Compose new message..." %>
  </div>
  
  
  
    <h4>Expires after:</h4> <h6>(default: Expires after 1 hour)</h6>
    <div class="grid-x grid-padding-x">
      <div class="cell small-1">
        <%= label_tag(:days, "Days:") %> 
        <%= text_field_tag(:days) %>
      </div>
      <div class="cell small-1">
        <%= label_tag(:hours, "Hours:") %>
        <%= text_field_tag(:hours) %>
      </div>
      <div class="cell small-1">
        <%= label_tag(:minutes, "Minutes:") %>
        <%= text_field_tag(:minutes) %>
      </div>
      <div class="cell small-1">
        <%= label_tag(:seconds, "Seconds:") %>
        <%= text_field_tag(:seconds) %>
      </div>
    </div>
  
  <BR>    

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>

  <BR><BR>
  
  <h2>Hi, <%= @user.name %>!</h2>

  <p id="notice"><%= notice %></p>
  
  <%= link_to 'New Post', new_post_path, class: "button alert" %>
  
  <BR><BR>
    
  <h3 class="blockquote-title">Your unread messages</h3>
  
  <% @posts.each do |post| %>
    <% 
    leidos = @user.readed_posts
    if leidos == nil
      leidos = ""
    end
    cadena = " " + post.id.to_s + " "
    if leidos.include? cadena 
    else %>
      <BR>
      <blockquote>
        <p class="blockquote-content">
        <%= post.user.name %>: <BR>
        <%= post.text %> <BR>

        <%= form_for(post, url: post_update_read_post_path(post.id)) do |f| %>
            <%= hidden_field_tag(:value, post.id) %>
            <%= f.submit "Mark as read", class: "button small"%>
        <% end %>    
        </p>
      </blockquote>
    <% end %>
  <% end %>

<% else %>  
  <BR><BR>
  <h2>All posts</h2>
  <p id="notice"><%= notice %></p>
  <% @posts.each do |post| %>
    <blockquote>
      <p class="blockquote-content">
        <%= post.user.name %>: <BR>
        <%= post.text %> <BR>
      </p>
    </blockquote>
  <% end %>
<% end %>
  
    

app/views/posts/new.html.erb
<BR>
<h2>New Post</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', root_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Expires at:</strong>
  <% hora = @post.expires_at - 5.hours %>
  <%= hora.strftime('%D - %T') %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>

app/views/users/edit.html.erb
<h1><%= @user.name %></h1>

<p id="notice"><%= notice %></p>


<%= link_to 'New Post', new_post_path %>

<BR><BR>
  
<%= current_user.email %>

  <h1 class="blockquote-title">Mensajes</h1>
<% @posts.each do |post| %>
  <% 
    paraMostrar = current_user.prueba.split(', ')
    paraMostrar.each do |numPost|  
      if post.id == numPost.to_i %>
        <BR>
        <blockquote>
          <p class="blockquote-content">
          <%= post.title %> <BR>
          <%= post.text %> <BR>
          <%= post.user.name %>
          <%= form_for(@user) do |f| %>
            <div class="actions">
              <%= f.submit "Mark as read", class: "btn btn-primary"%>
            </div>
          <% end %>    
          </p>
        </blockquote>
      <% end %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h2>All posts</h2>

  <% @posts.each do |post| %>
    <BR>
    <blockquote>
      <p class="blockquote-content">
      <%= post.user.name %>: <BR>
      <%= post.text %> <BR>
      </p>
    </blockquote>
  <% end %>

app/views/users/show.html.erb
<h2>Hi, <%= @user.name %>!</h2>

<p id="notice"><%= notice %></p>

<%= link_to 'New Post', new_post_path, class: "button secondary" %>

<BR><BR>
  

  <h3 class="blockquote-title">Your unread messages</h3>
  
  <% @posts.each do |post| %>
    <% 
    leidos = @user.prueba
    if leidos == nil
      leidos = ""
    end
    cadena = " " + post.id.to_s + " "
    if leidos.include? cadena 
    else %>
      <BR>
      <blockquote>
        <p class="blockquote-content">
        <%= post.user.name %>: <BR>
        <%= post.text %> <BR>

        <%= form_for(@user, url: user_update_read_post_path(@user.id)) do |f| %>

            <%= f.label :name %>
            <%= hidden_field_tag(:name, post.id) %>
            
            <%= f.submit "Mark as read", class: "btn btn-primary"%>
          </div>
        <% end %>    
        </p>
      </blockquote>
    <% end %>
  <% end %>